language: node_js
node_js:
  - "4.0"
install:
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - bower install
script:
  - gulp html-lint
  - gulp --travis
  - bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/CJSCommonPlatform/ngGovUk.git
  - secure: "cgzym808fPRadKz1LwaQ+X+yKdP0WRbgkIJaiQf96q8M7GNiaH6RK282ZHMHnUb6wjFRwMxplgiGEgNTFNbQHX9Bn34Gvb3CtsOh00Nt9NS63bO8psmwHeYAMZwlaaASNTyIz0JlX2MviCfn3F1nbJah0GpEuFbgG2dD8TYi3oDqiuMyW3vbW3KGBTPeZgNAYyHJnWf+KsUCp39HJx9Z/52/OBoiVbclL6hKdQbwDU0MMcan2XSv4WGji1rhKz/2zrY/vJlEL0tU/NGoEstYMaJ6mce/t00eYeZePO1ks8QV2KHSCXZSuXyxAjzHeeMhCSv/L5wHZamgKsUXEqoxefiQLTtM2HHr9XHM9hgmP245X2Ay7Yl+TiNZ9SmVCD8CgUi1uoJp/es6SiLmGGdebYBaOZgyDuecSJSCyF3Wyz21pOnHeOc2QOLDGqwExdzRKlUGfRFeS+twzIP6zwomuiYC1y79wghVFTgTWXHldwnSDF2OfvAIB30FUaRbAAZYVwamOTP2lgmtbzjOjUWqM4FhMOkEhycIoXIs5OsVtb1s0lasmBsYm1evSzXuFSBBi4sRDaOCz8fr2RTq5e2ei0Ty+QNS3m9MshVlGjksQ0gha5+Bi2Bog/bPzstreUvMVBWOChD4sUGa3EYKB+8v5B4Fl2dBqgeLRBYIqUYwJoI="